name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
      - staging
  pull_request:
    branches:
      - main
      - develop
      - staging

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest bandit

      - name: Rodar os testes
        run: |
          PYTHONPATH=todo_project pytest -v

      - name: Análise Estática com Bandit
        run: |
          bandit -r todo_project -lll

      - name: Análise de Dependência com OWASP
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'Task-Manager-using-Flask'
          path: '.'
          format: 'HTML'
          out: 'reports'

      - name: Upload Relatório OWASP
        uses: actions/upload-artifact@v3
        with:
          name: dependency-report
          path: reports/dependency-check-report.html
