name: DAST com ZAP

on:
  push:
    branches: [main, develop, staging]
  pull_request:
    branches: [main, develop, staging]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checar código do repositório
        uses: actions/checkout@v3

      - name: Configurar Docker
        run: sudo apt-get install docker.io

      - name: Build Docker image
        run: docker build -t my-flask-app .

      - name: Rodar a aplicação Flask
        run: |
          docker run -d -p 5000:5000 my-flask-app
          sleep 10  # Espera a aplicação levantar antes de rodar o ZAP

      - name: Rodar OWASP ZAP
        run: |
          docker pull owasp/zap2docker-stable
          docker run -t owasp/zap2docker-stable zap-baseline.py -t http://localhost:5000 -g gen.conf -r zap_report.html

      - name: Parar o container Flask
        run: docker stop $(docker ps -q)

      - name: Upload ZAP report
        uses: actions/upload-artifact@v2
        with:
          name: zap-report
          path: zap_report.html
