name: DAST com ZAP

on:
  push:
    branches: [main, develop, staging]
  pull_request:
    branches: [main, develop, staging]

jobs:
  dast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Criar rede Docker
        run: docker network create zap-net

      - name: Build da imagem Flask
        run: docker build -t flask-app .

      - name: Subir aplicação Flask na rede zap-net
        run: |
          docker run -d --rm --name flask-app --network zap-net -p 5000:5000 flask-app

      - name: Verificar se o Flask está respondendo
        run: |
          echo "Esperando o Flask responder..."
          for i in {1..20}; do
            if docker run --rm --network zap-net curlimages/curl:latest curl -s http://flask-app:5000 > /dev/null; then
              echo "Flask está online!"
              break
            fi
            echo "Tentativa $i falhou, tentando novamente..."
            sleep 3
          done

      - name: Criar pasta de relatórios
        run: mkdir -p zap_reports

      - name: Ajustar permissões do diretório de relatórios
        run: chmod -R 777 zap_reports

      - name: Rodar ZAP apontando para o flask-app
        run: |
          flask_ip=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' flask-app)
          docker run --rm \
            --network zap-net \
            -v $(pwd)/zap_reports:/home/zap/:rw \
            -v $(pwd)/zap_reports:/zap/wrk:rw \
            ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
            -t http://$flask_ip:5000 \
            -J /home/zap/report_json.json \
            -w /home/zap/report.md \
            -r /home/zap/report.html
