name: DAST com ZAP

on:
  push:
    branches:
      - main
      - develop
      - staging
  pull_request:
    branches:
      - main
      - develop
      - staging

jobs:
  dast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Criar rede Docker personalizada
        run: docker network create zap-net

      - name: Construir imagem da aplicação Flask
        run: docker build -t flask-app .

      - name: Subir aplicação Flask em background na rede zap-net
        run: |
          docker run -d --network zap-net --name flask-app flask-app
          sleep 10

      - name: Rodar ZAP Scan na mesma rede
        run: |
          docker run --rm --network zap-net \
            -v $(pwd):/zap/wrk/:rw \
            ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
            -t http://flask-app:5000 \
            -J report_json.json \
            -w report_md.md \
            -r report_html.html \
            -a

      - name: Upload do relatório HTML
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: report_html.html

      - name: Encerrar container do Flask
        run: docker stop flask-app
