name: DAST com ZAP

on:
  push:
    branches: [main, develop, staging]
  pull_request:
    branches: [main, develop, staging]

jobs:
  dast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Criar rede Docker personalizada
        run: docker network create zap-net

      - name: Construir imagem da aplicação Flask
        run: docker build -t flask-app .

      - name: Subir aplicação Flask em background na rede zap-net
        run: |
          docker run -d --rm --network zap-net --name flask-app flask-app

      - name: Verificar se o Flask está respondendo
        run: |
          for i in {1..10}; do
            if docker run --rm --network zap-net curlimages/curl http://flask-app:5000; then
              echo "Flask pronto!"
              break
            fi
            echo "Aguardando o Flask subir..."
            sleep 3
          done

      - name: Criar pasta de relatórios com permissões adequadas
        run: |
          mkdir -p zap_reports
          chmod 777 zap_reports

      - name: Rodar ZAP Scan na mesma rede
        run: |
          docker run --rm --network zap-net \
            -v $(pwd)/zap_reports:/zap/wrk/:rw \
            ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
            -t http://flask-app:5000 \
            -J report_json.json \
            -w report_md.md \
            -r report_html.html \
            -a

      - name: Upload do relatório HTML
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap_reports/report_html.html
