name: DAST com ZAP

on:
  push:
    branches: [main, develop, staging]
  pull_request:
    branches: [main, develop, staging]

jobs:
  dast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Construir imagem da aplicação Flask
        run: docker build -t flask-app .

      - name: Subir aplicação Flask em background
        run: |
          docker run -d --rm --name flask-app -p 5000:5000 flask-app

      - name: Verificar se o Flask está respondendo
        run: |
          echo "Aguardando a aplicação Flask responder..."
          for i in {1..10}; do
            if curl -s http://localhost:5000 > /dev/null; then
              echo "Flask está rodando!"
              break
            fi
            echo "Tentando novamente ($i)..."
            sleep 3
          done

      - name: Criar pasta de relatórios com permissões adequadas
        run: |
          mkdir -p zap_reports
          chmod 777 zap_reports

      - name: Rodar ZAP Scan contra o app Flask
        run: |
          docker run --rm \
            --network="host" \
            -v $(pwd)/zap_reports:/zap/wrk/:rw \
            ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
            -t http://localhost:5000 \
            -J report_json.json \
            -w report_md.md \
            -r report_html.html \
            -a

      - name: Upload do relatório HTML
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap_reports/report_html.html
