name: DAST com ZAP

on:
  push:
    branches:
      - main
      - develop
      - staging
  pull_request:
    branches:
      - main
      - develop
      - staging

jobs:
  dast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Construir imagem da aplicação Flask
        run: |
          docker build -t flask-app .

      - name: Subir aplicação Flask em background
        run: |
          docker run -d -p 5000:5000 --name app flask-app
          sleep 10  # espera a aplicação subir

      - name: Rodar ZAP Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'http://localhost:5000'
          cmd_options: '-a'

      - name: Encerrar container
        run: docker stop app
