name: DAST com ZAP

on:
  push:
    branches: [main, develop, staging]
  pull_request:
    branches: [main, develop, staging]

jobs:
  dast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Criar rede Docker
        run: docker network create zap-net

      - name: Build da imagem Flask
        run: docker build -t flask-app .

      - name: Subir aplicação Flask na rede zap-net
        run: |
          docker run -d --name flask-app --network zap-net -p 5000:5000 flask-app

      - name: Ver logs do Flask
        run: docker logs flask-app

      - name: Verificar se o Flask está respondendo
        run: |
          echo "Esperando o Flask responder..."
          for i in {1..20}; do
            echo "Tentativa $i..."
            docker run --rm --network zap-net curlimages/curl:latest \
              curl -v --connect-timeout 5 http://flask-app:5000
            if [ $? -eq 0 ]; then
              echo "Flask está online!"
              break
            fi
            echo "Tentativa $i falhou, tentando novamente em 5s..."
            sleep 5
          done

      - name: Rodar ZAP e exibir resultados no terminal
        run: |
          flask_ip="flask-app"
          echo "Rodando ZAP contra o Flask em http://$flask_ip:5000"
          docker run --rm \
            --network zap-net \
            ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
            -t http://$flask_ip:5000 || echo "ZAP encontrou vulnerabilidades. Verifique o log acima."
