name: DAST com ZAP

on:
  push:
    branches: [main, develop, staging]
  pull_request:
    branches: [main, develop, staging]

jobs:
  dast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Criar rede Docker
        run: docker network create zap-net

      - name: Build da imagem Flask
        run: docker build -t flask-app .

      - name: Subir aplicação Flask na rede zap-net
        run: |
          docker run -d --rm --name flask-app --network zap-net flask-app

      - name: Verificar se o Flask está respondendo
        run: |
          echo "Esperando o Flask responder..."
          for i in {1..10}; do
            if docker run --rm --network zap-net curlimages/curl:latest curl -s http://flask-app:5000 > /dev/null; then
              echo "Flask está online!"
              break
            fi
            echo "Tentativa $i falhou, tentando novamente..."
            sleep 3
          done

      - name: Criar pasta de relatórios
        run: mkdir -p zap_reports

      - name: Rodar ZAP apontando para o flask-app
        run: |
          docker run --rm \
            --network zap-net \
            -v $(pwd)/zap_reports:/zap/wrk/:rw \
            ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
            -t http://flask-app:5000 \
            -J report_json.json \
            -w report_md.md \
            -r report_html.html \
            -a

      - name: Upload do relatório HTML
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap_reports/report_html.html
